"""Render the raster panels that the editable figures embed.

Only frozen artefacts are read:
  submission_repro_20260827/predictions_compact/maps/mpdd/s0_k1/metal_plate.npz
  data/mpdd_raw/MPDD/metal_plate/{train/good/029.png,test/scratches/026.png}

The 448x448 map is produced by the repository's own frozen post-processing
(scripts/validation_handoff_20260911/common.py::dists_to_maps: bilinear resize then
Gaussian sigma = 4). No value is regenerated by this script.

The default output directory is `assets/` next to this script, i.e. a location that is
not a local scratch directory, so `build.mjs` can run from a clean checkout.

  python scripts/figures_reference_matching_20260914/make_assets.py [--out <dir>]

`contours.json` (figure 1's editable contour polygons) is *not* produced here: it was
extracted once by the completed 2026-09-11 notation pass and is kept beside the assets
as a frozen input.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

import numpy as np
from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]

DATASET = "mpdd"
SEED, SHOT, CATEGORY = 0, 1, "metal_plate"
QUERY = "metal_plate/test/scratches/026.png"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--out", type=Path, default=HERE / "assets")
    args = parser.parse_args()
    root = args.root.resolve()
    out = args.out.resolve()
    out.mkdir(parents=True, exist_ok=True)

    spec = importlib.util.spec_from_file_location(
        "fig_common", root / "scripts/validation_handoff_20260911/common.py"
    )
    common = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = common
    spec.loader.exec_module(common)

    npz = (
        root
        / "submission_repro_20260827/predictions_compact/maps"
        / DATASET
        / f"s{SEED}_k{SHOT}"
        / f"{CATEGORY}.npz"
    )
    with np.load(npz, allow_pickle=False) as z:
        ids = [str(x) for x in np.asarray(z["sample_ids"]).reshape(-1)]
        idx = ids.index(QUERY)
        concat = np.asarray(z["concat_patch_map"][idx], dtype=np.float32)
        dino = np.asarray(z["dino_patch_map"][idx], dtype=np.float32)
        ref_ids = [str(x) for x in np.asarray(z["ref_ids"]).reshape(-1)]
        grid = tuple(int(x) for x in np.asarray(z["grid_size"]).reshape(-1))
        map_size = tuple(int(x) for x in np.asarray(z["map_size"]).reshape(-1))

    print("query index", idx, "grid", grid, "map_size", map_size, "ref_ids", ref_ids)

    maps = {}
    for name, patch in (("concat", concat), ("dino", dino)):
        m = common.dists_to_maps(patch.reshape(1, -1), 1, grid, map_size)[0]
        lo, hi = float(m.min()), float(m.max())
        norm = (m - lo) / (hi - lo) if hi > lo else np.zeros_like(m)
        maps[name] = norm
        print(name, "map range", round(lo, 6), round(hi, 6))

    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        from matplotlib import colormaps

        for name, arr in maps.items():
            for cmap in ("magma", "inferno"):
                fig = plt.figure(figsize=(4.48, 4.48), dpi=200)
                ax = fig.add_axes([0, 0, 1, 1])
                ax.imshow(arr, cmap=colormaps[cmap], vmin=0.0, vmax=1.0, interpolation="nearest")
                ax.set_axis_off()
                path = out / f"scoremap_{name}_{cmap}.png"
                fig.savefig(path, dpi=200, transparent=False)
                plt.close(fig)
                print("wrote", path, path.stat().st_size)
        np.save(out / "scoremap_concat_normalised.npy", maps["concat"])
    except Exception as exc:  # pragma: no cover - reported, never hidden
        print("MATPLOTLIB_FAILED", type(exc).__name__, exc)

    # The contour panel draws editable paths on top of the query image, in 448x448 space.
    qpath = root / "data/mpdd_raw/MPDD" / QUERY
    q = Image.open(qpath)
    print("query image size", q.size)
    q.convert("RGB").resize((448, 448), Image.BILINEAR).save(out / "query_026_448.png")
    print("wrote", out / "query_026_448.png")

    for n in ("000", "001", "029"):
        src = root / "data/mpdd_raw/MPDD/metal_plate/train/good" / f"{n}.png"
        im = Image.open(src).convert("RGB")
        im.resize((224, 224), Image.BILINEAR).save(out / f"support_{n}_224.png")
        print("support", n, "source size", im.size)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
